### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by omerlh** [samber/prometheus-query-js#9]
Hey
Can you please publish types package? It will be really helpful for typescript users :)

Thanks!

**Comment by samber** [comment]
Hi @omerlh,

Thanks for your request.

I just published a new version of the package (full TS): `npm install prometheus-query@beta`.

Please test it. I'm pretty confident, but since there is no QA on this package, 2 checks are better than 1 ;)

I made a small breaking change in API. Check the README from my PR => https://github.com/samber/prometheus-query-js/blob/chore-v3-migration-to-typescript/README.md

As soon we are ready to merge, I will document the API migration from v2 to v3.

**Comment by omerlh** [comment]
Yep, I can confirm it is working. 
Thank you so much for the quick response! Two small issues:

It seems that the constructor requires a lot of arguments without defaults:
```
new PrometheusDriver({
    endpoint: "http://localhost:9090",
    baseURL: "/api/v1",
    headers: {},
    auth: {
      username: "",
      password: ""
    },
    proxy: undefined,
    timeout: 6000,
    withCredentials: false,
    warningHook: (x => console.log(x))
  });
```

And to import the types it is a bit messy:
```
import  { InstantVector }  from 'prometheus-query/dist/types'
```

**Comment by samber** [comment]
Thanks @omerlh for your feedback.

Time to release!
